language: r
cache:
  directories:
  - _bookdown_files
  - $HOME/.npm
  - $HOME/.local/share/renv
  - $TRAVIS_BUILD_DIR/renv/library

pandoc_version: 2.1.1

env:
  global:
    - NETLIFY_SITE_ID=6b6a38b6-7523-4555-965a-fa5cdc9f7157
    # NETLIFY_AUTH_TOKEN set in travis settings
    - RENV_CONFIG_REPOS_OVERRIDE=https://demo.rstudiopm.com/all/__linux__/xenial/latest

before_install:
  - export COMMIT_MSG=$(echo "$TRAVIS_COMMIT_MESSAGE" | head -n1)
  - export DEPLOY_MSG="${TRAVIS_COMMIT:0:7} ${COMMIT_MSG:0:50}"
  - Rscript -e "renv::restore()"

script:
  - Rscript -e 'bookdown::render_book("index.Rmd", quiet = TRUE)'
  - cp _redirects _book/_redirects

before_cache:
- nvm install stable
- npm install netlify-cli -g

deploy:
  - provider: script
    script: netlify deploy --dir _book --prod --message "$DEPLOY_MSG"    
    skip_cleanup: true
    on:
      branch: master
  - provider: script
    script: netlify deploy --dir _book --message "$DEPLOY_MSG"    
    skip_cleanup: true
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH != "master"
