language: r
cran: https://cran.rstudio.com
cache:
  packages: false
  directories:
  - $HOME/.npm

before_install:
  # rm -rf package-lock.json node_modules
  - nvm install stable
  - npm install netlify-cli -g
  - export DEPLOY_MSG="${TRAVIS_COMMIT:0:7} ${TRAVIS_COMMIT_MESSAGE:0:70}"

env:
  - NETLIFY_SITE_ID=82ff5a18-8a13-4f25-b688-230b04bc5664
  # R_REMOTES_STANDALONE=true
  # NETLIFY_AUTH_TOKEN set in travis settings

script:
- Rscript -e 'bookdown::render_book("index.Rmd")'

deploy:
  - provider: script
    script: netlify deploy --dir _book --prod --message "$DEPLOY_MSG"
    skip_cleanup: true
    on:
      branch: master
  - provider: script
    script: netlify deploy --dir _book --message "$DEPLOY_MSG"
    skip_cleanup: true
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH != "master"